### ISSUE TITLE
Add Scrollbar to Ensure Preview Visibility

### ISSUE THREAD

**Issue by Husain-Malwat** [Kishan-Ved/resume_generator#11]
Add a scrollbar to the resume preview to ensure it remains visible while filling out the form. The proposed change involves adding the following CSS to the .cv-form class:

```
.cv-form {
    height: 100vh;
    overflow-y: scroll;
}

```

**Comment by Kishan-Ved** [comment]
Hi! Thanks for this suggestion. Please let me know if you are making a PR for this, or I'll do it.

**Comment by Kishan-Ved** [comment]
Closing with reference to: https://github.com/Kishan-Ved/resume_generator/pull/12
