### ISSUE TITLE
footer updation 

### ISSUE THREAD

**Issue by Madan2468** [Kishan-Ved/resume_generator#15]
#### footer is not good looking 
The footer of the website can be evolved by adding icons and making changes in the ui , for the reference of what I am taking about I am attaching the my footer work for the reference which would make the things more clear.
<img width="1253" alt="Screenshot 2024-09-29 at 11 07 03 PM" src="https://github.com/user-attachments/assets/01b717e8-25c0-4aef-89e2-43087438eb43">

**Comment by Kishan-Ved** [comment]
Yes, you can go ahead with this. Please include all the information that is present in the current footer (including all the hyperlinks)

**Comment by Madan2468** [comment]
sure. Kindly assign me this issue under Hacktoberfest 2024.

**Comment by Kishan-Ved** [comment]
Done, please go ahead with this. Thanks!

**Comment by Madan2468** [comment]
sure.

**Comment by Kishan-Ved** [comment]
Completed in #19
