### ISSUE TITLE
Add an achievements section

### ISSUE THREAD

**Issue by Kishan-Ved** [Kishan-Ved/resume_generator#16]
#### Description of the problem

This should be an optional section, just like the skills section

This should allow multiple entries using the Add this button

**Comment by priyamaggarwal18** [comment]
Hi @Kishan-Ved  I think I can work with this section as I have a good knowledge of Latex code.

**Comment by Kishan-Ved** [comment]
I have assigned it to you, please go ahead and make a PR. Thanks!

**Comment by Kishan-Ved** [comment]
Closing this with respect to: https://github.com/Kishan-Ved/resume_generator/pull/21
