### ISSUE TITLE
Improve `index.html` page

### ISSUE THREAD

**Issue by Kishan-Ved** [Kishan-Ved/resume_generator#17]
#### Description of the problem

index.html should ideally be the first page that the user visits when he opens this website, it should provide all the info and an example of the created resume. The UI can be improved, current state: https://kishan-ved.github.io/resume_generator/index.html

It will be nice to have a pdf displayed instead of the image of the example resume. Or any other alternative that makes the text clear will do.

Also, it should be responsive.

**Comment by JollyJolli** [comment]
Hey there! I want to work on this

**Comment by Kishan-Ved** [comment]
Thanks, I have assigned this issue to you.

**Comment by Kishan-Ved** [comment]
Completed in: https://github.com/Kishan-Ved/resume_generator/pull/35

Although this issue is closed, we can have more updates to the index.html page and make it better. Submit a PR if you have an idea.
