### ISSUE TITLE
Remove icons in the preview

### ISSUE THREAD

**Issue by Kishan-Ved** [Kishan-Ved/resume_generator#22]
#### Description of the problem

Currently, the preview has these icons:
![image](https://github.com/user-attachments/assets/8db330b3-fa39-4e26-9780-d40acef9f00e)

Replace them with text having hyperlinks as shown below
![image](https://github.com/user-attachments/assets/3c283fa7-b4cb-4ccc-8c15-13a8073b55db)

**Comment by jfmartinz** [comment]
I'll give it a try, can you please assign me this issue?

**Comment by Arshad-ashuu** [comment]
I would like to work on this issue. Can you please assign me with this @Kishan-Ved

**Comment by Kishan-Ved** [comment]
Assuming that both of you are here for Hacktoberfest: Let's do this on a first come first serve basis. 

Make a PR and I will merge the first valid PR and assign it to you.

**Comment by Kishan-Ved** [comment]
NOTE: All three (LinkedIn, GitHub and Website) should be hyperlinked in the preview and must redirect to the link entered in the form.
