### ISSUE TITLE
Website URL not mentioned in the live editor

### ISSUE THREAD

**Issue by VivekRaj2005** [Kishan-Ved/resume_generator#26]
#### Description of the problem
The field website needs to update something in the live editor, as the field for the website needs to be added, along with GitHub and LinkedIn. 

#### Example of the problem
Current Behaviour
![Current Behaviour](https://github.com/user-attachments/assets/90961bf9-52e4-46a6-9e2b-52b8bd0ed6f6)

Expected Behaviour
![Expected Behaviour](https://github.com/user-attachments/assets/01dd1250-2cf6-48af-8647-b01cfeeb6464)

#### Comments
I have already worked on a solution. Please mark this as HacktoberFest. Also, please assign me the issue

**Comment by VivekRaj2005** [comment]
I just read issue #22. I have updated them to links as follows:

![image](https://github.com/user-attachments/assets/abd0db35-69f6-4b63-bcc2-df59ea2cba69)

The website href also gets updated, like LinkedIn and GitHub.
Please close the issue if it has already been fixed. 
If not, my fix is ready to be pushed, and I can open a pull request. Please inform me at the earliest.

**Comment by Kishan-Ved** [comment]
You can make a PR. There is another PR working on this, I will merge the first valid PR.

If your PR is merged, I will assign the hacktoberfest label.

**Comment by Kishan-Ved** [comment]
Closing with reference to: https://github.com/Kishan-Ved/resume_generator/pull/24
