### ISSUE TITLE
Change of Workflow of Software while adding Masters and PhD to Resume

### ISSUE THREAD

**Issue by VivekRaj2005** [Kishan-Ved/resume_generator#27]
#### Description of the problem

PhD and Masters are being displayed anyway in the live preview. 

The field is attached with a side note: If you don't want to add this, leave the institute field blank. It won't be included in the LaTeX code, though it is seen as blank in the preview.

I want to enhance the feature by showing the PhD Feild only if the person checks the PhD checkbox and the Master Feild only if the Master's Checkbox is checked. 

#### Comments
If this is a valid enhancement to the Resume Generator, please inform me; otherwise, please close the issue. I'm currently working on the enhancement. Please mark this as HacktoberFest. And also, please assign me the problem.

**Comment by Kishan-Ved** [comment]
This is a good issue. Please work on this.

**Comment by Kishan-Ved** [comment]
Are you working on this? @VivekRaj2005

**Comment by yuvraj-rathod-1202** [comment]
If @VivekRaj2005  is not working on this, Can I start to work on this.

**Comment by Anurag519Narula** [comment]
@Kishan-Ved can i work on this issue if it is not assigned?

**Comment by Kishan-Ved** [comment]
Yes, please work on this and make a PR.

**Comment by Kishan-Ved** [comment]
Completed in #52
