### ISSUE TITLE
Unable to delete or edit an existing INTERNSHIP or PROJECT

### ISSUE THREAD

**Issue by VivekRaj2005** [Kishan-Ved/resume_generator#28]
#### Description of the problem
The software is unable to delete or edit an existing INTERNSHIP or PROJECT. This would be a very good feature update for the Resume Generator, in my opinion.

#### Comments
If this is a valid enhancement to the Resume Generator, please let me know; if not, please close the issue. I'm currently working on the enhancement. Please mark this as HacktoberFest. And also, please assign me the problem.

**Comment by Kishan-Ved** [comment]
This is a good issue. Please work on this. Make existing internships and projects editable and deletable.

**Comment by Kishan-Ved** [comment]
Edit option added in #33

**Comment by Kishan-Ved** [comment]
Completed in:

https://github.com/Kishan-Ved/resume_generator/pull/33

https://github.com/Kishan-Ved/resume_generator/pull/36
