### ISSUE TITLE
Add an ML model to enhance text

### ISSUE THREAD

**Issue by Kishan-Ved** [Kishan-Ved/resume_generator#30]
#### Description of the problem

Once the user enters the description of his/her project or internship, there should be an ENHANCE TEXT button that improves the text entered.

Note: The model used should be free of cost. You can use exiting APIs of already trained models / chatbots.

**Comment by Reckadon** [comment]
I'm thinking of using the Groq API to implement this, how should we handle the Groq API key in this case? I can put the key in a secrets file and use it in the code. Will this be fine? thanks

**Comment by Kishan-Ved** [comment]
Hi @Reckadon , I haven't used Groq AI, so I'm unable to help. If the solution is free of cost, it can be used. You can submit a PR if you're interested. Thanks!

**Comment by Reckadon** [comment]
@Kishan-Ved the main issue is how to securely store the secret API key. Since the project uses frontend javascript only, there is no way to do that other than to just paste the key in the javascript file directly.

**Comment by Reckadon** [comment]
I have completed this feature request #48 , you can try it by getting a GroqAPI key from [here](https://console.groq.com/keys) and putting it a secrets.json file as described in the PR's comment.
