### ISSUE TITLE
Updating the UI of the landing page and making it responsive.

### ISSUE THREAD

**Issue by priyamaggarwal18** [Kishan-Ved/resume_generator#34]
Hi @Kishan-Ved, nice to meet you again. I believe I can contribute to the UI aspect of this project, as I am skilled in it and can improve the UI of the landing page.

I made a prototype of the design it looks like this
![Screenshot 2024-10-03 143614](https://github.com/user-attachments/assets/5e7e35c8-6de6-4425-9a69-5f234ee28b5f)

**Comment by Kishan-Ved** [comment]
Closing wrt: https://github.com/Kishan-Ved/resume_generator/pull/35
