### ISSUE TITLE
Change color of edit and delete buttons and fix grammatical errors

### ISSUE THREAD

**Issue by Kishan-Ved** [Kishan-Ved/resume_generator#38]
#### Description of the problem

![image](https://github.com/user-attachments/assets/4e0cf110-b1a2-494a-8473-52875043c32d)

1) Change the color of buttons from blue to black (with white text, just like all the other buttons)

2) Change the text above the buttons to:
- If you want to edit an internship, click on edit.
- If you want to delete an internship, click on delete.

[ Do the above 2 points for projects too ]

**Comment by TEJAS07080** [comment]
@Kishan-Ved can i work on this?

**Comment by Kishan-Ved** [comment]
Sure, please go ahead and submit a PR.

**Comment by TEJAS07080** [comment]
@Kishan-Ved in your resumegenerator.html file I'm unable locate the Edit and Delete button. Kindly help

**Comment by Kishan-Ved** [comment]
Add an internship (fill in the details and click on the add this button), then, you will be able to see the edit and delete buttons

**Comment by TEJAS07080** [comment]
i have submitted a pull request regarding the same, kindly review

**Comment by Kishan-Ved** [comment]
Completed in https://github.com/Kishan-Ved/resume_generator/pull/40
