### ISSUE TITLE
Make Internships section optional

### ISSUE THREAD

**Issue by Kishan-Ved** [Kishan-Ved/resume_generator#41]
#### Description of the problem

Currently, we display "DELETE THIS" text if a section is blank.
![image](https://github.com/user-attachments/assets/bdcb7553-3062-4a19-8cd5-98443b4b8938)

Many people will be generating resumes for the first time, hence, we can keep the internship section optional. Add a checkbox, and if it is ticked, the form (on the left side) for internship details should appear. If the check box is ticked, user's internship data should be visible in the preview and the latex code should have an internship section. If the checkbox is not ticked, the preview and the latex code shouldn't have an internship section.

**Comment by vizzv** [comment]
@Kishan-Ved I want to contribute to this.Can you assign it

**Comment by Kishan-Ved** [comment]
Completed in https://github.com/Kishan-Ved/resume_generator/pull/46

**Comment by Kishan-Ved** [comment]
> @Kishan-Ved I want to contribute to this.Can you assign it

Sorry, this issue has been solved. You can work on other issues. PRs are merged on a first come first serve basis.
