### ISSUE TITLE
Italics text below projects to be displayed in preview

### ISSUE THREAD

**Issue by Kishan-Ved** [Kishan-Ved/resume_generator#9]
Italics text below projects to be displayed in preview. Currently, nothing is displayed.

**Comment by Ryadav0654** [comment]
Hi @Kishan-Ved ,

I would like to work on this issue. Could you please assign it to me?

Thank you!

**Comment by Kishan-Ved** [comment]
I have assigned it to you, please go ahead and make a PR. Thanks!

**Comment by Ryadav0654** [comment]
Hi @Kishan-Ved ,

I have created this pull request with the following updates:
- Added italic text below the titles in the Internship and Project sections.
- Included project links in both sections for better accessibility.

Could you please review the changes when you have time? Your feedback would be appreciated!

Thanks!

**Comment by Kishan-Ved** [comment]
Closing this with respect to: https://github.com/Kishan-Ved/resume_generator/pull/20
